DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE BOOKS(id BIGINT auto_increment PRIMARY KEY, name VARCHAR(255), authorId INT, genreId INT);
CREATE TABLE AUTHORS(authorId BIGINT auto_increment PRIMARY KEY, nameAuthor VARCHAR(255));
CREATE TABLE GENRES (genreId BIGINT auto_increment PRIMARY KEY, nameGenre VARCHAR(255));
